# Project Portfolio Analytics Dashboard

Power BI dashboard for portfolio-level delivery monitoring, risk analysis, and corrective-action prioritization.

## Overview

This project simulates a PMO reporting environment and turns portfolio data into a decision-support dashboard built with Power BI and Python.

It is designed to help answer three practical questions:

- Which programs are underperforming on delivery?
- Where is risk concentrated across the portfolio?
- Which projects or milestone phases should be prioritized for corrective action?

## Why This Project Matters

This dashboard is designed to support portfolio-level decision-making, not just project tracking.

It helps PMO analysts, portfolio managers, and program leaders:
- identify where delivery risk is concentrated,
- isolate the main drivers of slippage,
- compare execution performance across the portfolio,
- prioritize corrective action more effectively.

## Dashboard Pages

| Page | Purpose |
|---|---|
| Portfolio Overview | High-level view of portfolio health, status distribution, and issue concentration |
| Delivery Performance | Execution trends, schedule slippage, and underperforming areas |
| Risk Analysis | Risk exposure, severity, and drivers of delivery pressure |

## Screenshots

### Portfolio Overview
![Portfolio Overview](portfolio_overview.png)

### Delivery Performance
![Delivery Performance](delivery_performance.png)

### Risk Analysis
![Risk Analysis](risk_analysis.png)

<details>
<summary><strong>Dashboard Navigation and Cross-Page Analysis</strong></summary>

The report is designed as a connected analytical workflow rather than a set of isolated pages. Each page addresses a different portfolio management question, while shared filters preserve the same analytical scope across the dashboard.

Users can begin with a high-level portfolio view, move to delivery execution analysis, and then examine risk concentration without losing context.

### How the Pages Connect

- Portfolio Overview provides the overall picture of portfolio health, project status, and concentration of issues.
- Delivery Performance focuses on execution trends, schedule slippage, and delivery performance across projects or programs.
- Risk Analysis highlights risk exposure, severity, and the main sources of delivery pressure.

### Shared Filters Across Pages

The dashboard uses shared slicers to maintain a consistent decision perimeter across pages.

Common filters may include:
- reporting period,
- project status,
- program or portfolio segment,
- business area,
- risk level.

When a user applies a filter on one page, that context is preserved while navigating to the others. As a result:
- visuals remain aligned on the same subset of projects,
- KPI comparisons stay consistent across report pages,
- users can move from summary to detail without resetting their analysis.

</details>

<details>
<summary><strong>Business Context and Objective</strong></summary>

## Business Context

This project was designed as a portfolio management decision-support dashboard for a PMO or transformation office overseeing multiple programs and projects.

The objective is not only to track project status, but to identify where delivery risk is concentrated, which programs require escalation, and which project phases contribute most to delays.

## Objective

Build a Power BI dashboard that helps decision-makers answer three critical questions:

1. Which programs are underperforming on delivery?
2. Where is risk concentrated across the portfolio?
3. Which projects and milestone phases should be prioritized for corrective action?

## Target Audience

- PMO analysts
- Portfolio managers
- Program directors
- Transformation leaders

## Analytical Scope

The dashboard covers three complementary dimensions of portfolio performance:

- delivery performance,
- risk exposure,
- budget and delay impact.

</details>

<details>
<summary><strong>Key KPIs</strong></summary>

- On-time delivery rate: share of projects delivered on or before target date
- Budget variance: difference between actual and planned budget
- Delay impact: cumulative delay generated by late projects
- High-risk project ratio: share of projects flagged as high risk
- Top delay contributors: projects accounting for the largest share of total delay impact

</details>

<details>
<summary><strong>Data Model</strong></summary>

The model follows a star schema structure to support KPI consistency, scalable filtering, and drill-down analysis.

The dashboard relies on a relational model connecting projects, milestones, risks, and resources to support portfolio-level analysis.

![Data Model](data_model.png)

</details>

<details>
<summary><strong>Data Preparation Workflow</strong></summary>

The reporting workflow follows five steps:

1. Generate realistic portfolio data using Python
2. Run sanity checks across projects, milestones, and risks
3. Enrich the datasets for reporting use cases
4. Build the data model in Power BI
5. Design KPI-driven dashboard pages for executive and operational analysis

This workflow helps move from simulated raw records to structured, analysis-ready reporting tables.

</details>

<details>
<summary><strong>Key Insights</strong></summary>

The dashboard is designed to support a portfolio-level reading of delivery performance rather than a purely descriptive project review.

It helps surface insights such as:
- which parts of the portfolio concentrate the highest proportion of projects under pressure,
- whether delivery slippage appears isolated or systemic across programs,
- which at-risk projects combine weak delivery performance with elevated risk exposure,
- where portfolio managers may need to prioritize escalation or corrective action.

Taken together, these insights help shift the dashboard from status reporting to management support.

</details>

<details>
<summary><strong>Recommendations</strong></summary>

- Prioritize corrective action on the top delayed projects rather than spreading attention evenly across the portfolio.
- Review milestone governance in Planning and Testing phases to reduce repeated execution bottlenecks.
- Use targeted program reviews for underperforming areas instead of portfolio-wide generic escalation.
- Track delivery and risk indicators together to anticipate execution slippage earlier.

</details>

## Tools and Skills

### Tools Used

- Power BI
- DAX
- Python
- Pandas
- GitHub

### Skills Demonstrated

- KPI design for portfolio management
- Power BI dashboard development
- Star schema modeling
- Business-oriented data storytelling
- Python-based data preparation
- Risk and delivery performance analysis

<details>
<summary><strong>Reproducibility</strong></summary>

The project can be reproduced from the Python scripts and CSV outputs included in this repository.

### Steps

1. Run `1_generate_portfolio_data.py` to generate the base portfolio datasets
2. Run `2_sanity_checks.py` to validate data consistency across projects, milestones, and risks
3. Run `3_enrich_data.py` to create reporting-ready datasets for the dashboard
4. Open the Power BI file and connect it to the generated files in the `data/` folder

### Requirements

- Python 3.x
- pandas
- Power BI Desktop
- Access to the files stored in the `data/` folder

</details>

<details>
<summary><strong>Project Structure</strong></summary>

- `1_generate_portfolio_data.py` -> portfolio data generation
- `2_sanity_checks.py` -> validation and consistency checks
- `3_enrich_data.py` -> reporting-oriented enrichment
- `data/` -> generated CSV datasets
- `project-portfolio-analytics-dashboard.pbix` -> Power BI report file
- `portfolio_overview.png` -> dashboard screenshot
- `delivery_performance.png` -> dashboard screenshot
- `risk_analysis.png` -> dashboard screenshot
- `data_model.png` -> data model screenshot

</details>

<details>
<summary><strong>Notes</strong></summary>

The data used in this project is simulated for demonstration purposes.

The emphasis is on analytical reasoning, KPI design, transformation logic, dashboard structure, and business-oriented interpretation in a realistic PMO reporting scenario.

</details>
